In [28]:
# import os
# # folder_path='/home/python/higashi/cool/contacts_map_250k/cortex'
# folder_path='/home/python/higashi/cool/contacts_map_250k/cortex/cortex_p1'
# # def sort_key(path):
# #     # 获取路径中的数字部分作为排序关键字
# #     return [int(part) if part.isdigit() else part for part in path.split('_')]
# def sort_key(path):
#     # 先使用斜杠分割路径，然后使用下划线分割每个部分，获取数字作为排序关键字
#     parts = []
#     for part in path.split('/'):
#         parts.extend(part.split('_'))
#     return [int(part) if part.isdigit() else part for part in parts]
# def find_file(folder_path):
#     file_path=[]
#     for root, dirs, files in os.walk(folder_path):
#             for file in files:
#                 if file.endswith('.txt') and 'chr1' == file.split(".")[0]:
#                     file_path.append(os.path.join(root, file))
#                     # print(file_path)
#     return file_path
# paths=find_file(folder_path)
# sorted_paths = sorted(paths, key=sort_key)

# # # 打印排序后的路径
# for path in sorted_paths:
#     print(path)

/home/python/higashi/cool/contacts_map_250k/cortex/cortex_p1/cortex_p1_1/chr1.txt
/home/python/higashi/cool/contacts_map_250k/cortex/cortex_p1/cortex_p1_2/chr1.txt
/home/python/higashi/cool/contacts_map_250k/cortex/cortex_p1/cortex_p1_3/chr1.txt
/home/python/higashi/cool/contacts_map_250k/cortex/cortex_p1/cortex_p1_4/chr1.txt
/home/python/higashi/cool/contacts_map_250k/cortex/cortex_p1/cortex_p1_5/chr1.txt
/home/python/higashi/cool/contacts_map_250k/cortex/cortex_p1/cortex_p1_6/chr1.txt
/home/python/higashi/cool/contacts_map_250k/cortex/cortex_p1/cortex_p1_7/chr1.txt
/home/python/higashi/cool/contacts_map_250k/cortex/cortex_p1/cortex_p1_8/chr1.txt
/home/python/higashi/cool/contacts_map_250k/cortex/cortex_p1/cortex_p1_9/chr1.txt
/home/python/higashi/cool/contacts_map_250k/cortex/cortex_p1/cortex_p1_10/chr1.txt
/home/python/higashi/cool/contacts_map_250k/cortex/cortex_p1/cortex_p1_11/chr1.txt
/home/python/higashi/cool/contacts_map_250k/cortex/cortex_p1/cortex_p1_12/chr1.txt
/home/python/

In [32]:
# from scipy.sparse import csr_matrix
# path='/home/python/higashi/cool/contacts_map_250k/cortex/cortex_p1/cortex_p1_1/chr1.txt'
# with open(path, 'r') as f:
#     lines = f.readlines()

# # 将文本数据解析为稀疏矩阵的坐标和值
# rows = []
# cols = []
# values = []

# # for line in f.strip().split('\n'):
# for line in lines:
#     row, col, value = map(int, line.split())
#     rows.append(row)
#     cols.append(col)
#     values.append(value)

# # 创建稀疏矩阵
# sparse_matrix = csr_matrix((values, (rows, cols)), shape=(max(rows)+1, max(cols)+1))

# print("稀疏矩阵：")
# print(sparse_matrix.toarray())


稀疏矩阵：
[[ 0  0  0 ...  0  0  0]
 [ 0  0  0 ...  0  0  0]
 [ 0  0  0 ...  0  0  0]
 ...
 [ 0  0  0 ... 21  7  0]
 [ 0  0  0 ...  7 11  0]
 [ 0  0  0 ...  0  0  1]]


In [40]:
# paths=['/home/python/higashi/cool/contacts_map_250k/cortex/cortex_p1/cortex_p1_1/chr1.txt',
# '/home/python/higashi/cool/contacts_map_250k/cortex/cortex_p1/cortex_p1_2/chr1.txt',
# '/home/python/higashi/cool/contacts_map_250k/cortex/cortex_p1/cortex_p1_3/chr1.txt',
# '/home/python/higashi/cool/contacts_map_250k/cortex/cortex_p1/cortex_p1_4/chr1.txt',
# '/home/python/higashi/cool/contacts_map_250k/cortex/cortex_p1/cortex_p1_5/chr1.txt',
# '/home/python/higashi/cool/contacts_map_250k/cortex/cortex_p1/cortex_p1_6/chr1.txt']
# sparse_matrices_list=[]
# for path in paths:
#     with open(path, 'r') as f:
#         lines = f.readlines()

#     # 将文本数据解析为稀疏矩阵的坐标和值
#     rows = []
#     cols = []
#     values = []

#     for line in lines:
#         row, col, value = map(int, line.split())
#         rows.append(row)
#         cols.append(col)
#         values.append(value)

#     # 创建稀疏矩阵，使用lil_matrix进行高效构建
#     # 创建稀疏矩阵
#     sparse_matrix_csr = csr_matrix((values, (rows, cols)), shape=(max(rows)+1, max(cols)+1))

#     # 将稀疏矩阵添加到列表中
#     sparse_matrices_list.append(sparse_matrix_csr)

# # 将稀疏矩阵列表保存为.npy文件
# np.save('test_sparse_matrices.npy', sparse_matrices_list)
# #/home/python/higashi/notebook/without_higahsi_test/test_sparse_matrices.npy

In [1]:
#不使用higashi直接由txt文件列表得到数据集按染色体存储的稀疏矩阵文件
import numpy as np
import os
from scipy.sparse import csr_matrix
from tqdm import tqdm

# def sort_key(path):
#     # 获取路径中的数字部分作为排序关键字
#     return [int(part) if part.isdigit() else part for part in path.split('_')]
def sort_key(path):
    # 先使用斜杠分割路径，然后使用下划线分割每个部分，获取数字作为排序关键字
    parts = []
    for part in path.split('/'):
        parts.extend(part.split('_'))
    return [int(part) if part.isdigit() else part for part in parts]
#获取数据集根目录下所以chrom命名的txt文件并返回排序后的文件列表
def find_file(folder_path):
    file_path=[]
    for root, dirs, files in os.walk(folder_path):
            for file in files:
                if file.endswith('.txt') and chrom == file.split(".")[0]:
                    file_path.append(os.path.join(root, file))
    sorted_paths = sorted(file_path, key=sort_key)
    return sorted_paths
#按染色体获取的排序后的文件列表文件逐个转换成稀疏矩阵格式添加到列表中，最后将列表保存为一个按染色体命名的npy文件
def txt_to_sparse(floder_path,chrom):
    #初始化要写入文件的列表为空仿真重复写入
    sparse_matrices_list=[]
    paths=find_file(folder_path)
    #添加进度条显示处理样本进度
    for path in tqdm(paths,desc="Processing %s"%chrom):
        with open(path, 'r') as f:
            lines = f.readlines()
        rows = []
        cols = []
        values = []
        for line in lines:
            row, col, value = map(int, line.split())
            rows.append(row)
            cols.append(col)
            values.append(value)
        sparse_matrix_csr = csr_matrix((values, (rows, cols)), shape=(max(rows)+1, max(cols)+1), dtype=np.float32)
        sparse_matrices_list.append(sparse_matrix_csr)
    np.save(os.path.join(output_dir,'%s_sparse_matrices.npy'% chrom), sparse_matrices_list)
    print (chrom, "finished")
#数据集全部稀疏矩阵txt文件根目录
folder_path='/home/python/higashi/cool/contacts_map_250k/cortex'
#存放输出结果路径
output_dir='/home/python/higashi/notebook/without_higahsi_test/tmp'
chrom_list = ["chr1","chr2","chr3","chr4","chr5",
    "chr6","chr7","chr8","chr9","chr10",
    "chr11","chr12","chr13","chr14","chr15",
    "chr16","chr17","chr18","chr19","chrX"]
chrom_list = np.array(chrom_list)
for chrom in chrom_list:
    txt_to_sparse(folder_path,chrom)
    


Processing chr1: 100%|██████████| 1075/1075 [00:28<00:00, 37.62it/s]


chr1 finished


Processing chr2: 100%|██████████| 1075/1075 [00:25<00:00, 42.11it/s]


chr2 finished


Processing chr3: 100%|██████████| 1075/1075 [00:22<00:00, 47.14it/s]


chr3 finished


Processing chr4: 100%|██████████| 1075/1075 [00:20<00:00, 52.63it/s]


chr4 finished


Processing chr5: 100%|██████████| 1075/1075 [00:19<00:00, 55.05it/s]


chr5 finished


Processing chr6: 100%|██████████| 1075/1075 [00:20<00:00, 52.73it/s]


chr6 finished


Processing chr7: 100%|██████████| 1075/1075 [00:18<00:00, 57.25it/s]


chr7 finished


Processing chr8: 100%|██████████| 1075/1075 [00:16<00:00, 63.68it/s]


chr8 finished


Processing chr9: 100%|██████████| 1075/1075 [00:16<00:00, 65.20it/s]


chr9 finished


Processing chr10: 100%|██████████| 1075/1075 [00:17<00:00, 60.25it/s]


chr10 finished


Processing chr11: 100%|██████████| 1075/1075 [00:16<00:00, 66.80it/s]


chr11 finished


Processing chr12: 100%|██████████| 1075/1075 [00:15<00:00, 68.30it/s]


chr12 finished


Processing chr13: 100%|██████████| 1075/1075 [00:16<00:00, 65.33it/s]


chr13 finished


Processing chr14: 100%|██████████| 1075/1075 [00:15<00:00, 68.93it/s]


chr14 finished


Processing chr15: 100%|██████████| 1075/1075 [00:13<00:00, 81.96it/s]


chr15 finished


Processing chr16: 100%|██████████| 1075/1075 [00:12<00:00, 84.05it/s]


chr16 finished


Processing chr17: 100%|██████████| 1075/1075 [00:11<00:00, 91.31it/s]


chr17 finished


Processing chr18: 100%|██████████| 1075/1075 [00:11<00:00, 92.36it/s]


chr18 finished


Processing chr19: 100%|██████████| 1075/1075 [00:07<00:00, 152.25it/s]


chr19 finished


Processing chrX: 100%|██████████| 1075/1075 [00:15<00:00, 71.60it/s]


chrX finished


In [56]:
my_sparse = np.load('/home/python/higashi/notebook/without_higahsi_test/tmp/chr1_sparse_matrices.npy', allow_pickle=True)
my_sparse

array([<782x782 sparse matrix of type '<class 'numpy.int64'>'
       	with 14887 stored elements in Compressed Sparse Row format>,
       <782x782 sparse matrix of type '<class 'numpy.int64'>'
       	with 11268 stored elements in Compressed Sparse Row format>,
       <782x782 sparse matrix of type '<class 'numpy.int64'>'
       	with 9442 stored elements in Compressed Sparse Row format>, ...,
       <782x782 sparse matrix of type '<class 'numpy.int64'>'
       	with 11065 stored elements in Compressed Sparse Row format>,
       <782x782 sparse matrix of type '<class 'numpy.int64'>'
       	with 13173 stored elements in Compressed Sparse Row format>,
       <782x782 sparse matrix of type '<class 'numpy.int64'>'
       	with 11021 stored elements in Compressed Sparse Row format>],
      dtype=object)

In [57]:
my_sparse = np.load('/home/python/higashi/dataset2/cortex/250k/tmp/raw/chr1_sparse_adj.npy', allow_pickle=True)
my_sparse

array([<782x782 sparse matrix of type '<class 'numpy.float32'>'
       	with 14887 stored elements in Compressed Sparse Row format>,
       <782x782 sparse matrix of type '<class 'numpy.float32'>'
       	with 11268 stored elements in Compressed Sparse Row format>,
       <782x782 sparse matrix of type '<class 'numpy.float32'>'
       	with 9442 stored elements in Compressed Sparse Row format>, ...,
       <782x782 sparse matrix of type '<class 'numpy.float32'>'
       	with 14587 stored elements in Compressed Sparse Row format>,
       <782x782 sparse matrix of type '<class 'numpy.float32'>'
       	with 13287 stored elements in Compressed Sparse Row format>,
       <782x782 sparse matrix of type '<class 'numpy.float32'>'
       	with 12003 stored elements in Compressed Sparse Row format>],
      dtype=object)

In [41]:
 origin_sparse = np.load('/home/python/higashi/notebook/without_higahsi_test/test_sparse_matrices.npy', allow_pickle=True)

In [49]:
origin_sparse[6]

IndexError: index 6 is out of bounds for axis 0 with size 6

In [38]:
print(sparse_matrix)

  (12, 12)	11
  (12, 15)	3
  (12, 16)	3
  (12, 25)	1
  (12, 27)	4
  (12, 29)	1
  (12, 106)	1
  (12, 107)	1
  (12, 114)	1
  (12, 115)	1
  (12, 116)	1
  (12, 124)	3
  (12, 188)	1
  (12, 191)	3
  (12, 192)	2
  (12, 193)	1
  (12, 197)	1
  (12, 198)	1
  (12, 199)	1
  (12, 353)	1
  (12, 487)	1
  (12, 521)	2
  (12, 544)	1
  (12, 549)	1
  (13, 13)	9
  :	:
  (778, 775)	6
  (778, 776)	7
  (778, 777)	9
  (778, 778)	18
  (778, 779)	2
  (778, 781)	1
  (779, 180)	1
  (779, 767)	1
  (779, 772)	1
  (779, 773)	1
  (779, 776)	5
  (779, 777)	1
  (779, 778)	2
  (779, 779)	21
  (779, 780)	7
  (780, 606)	1
  (780, 639)	1
  (780, 772)	1
  (780, 775)	1
  (780, 776)	1
  (780, 777)	1
  (780, 779)	7
  (780, 780)	11
  (781, 778)	1
  (781, 781)	1


In [ ]:
#scipy.sparse.csr.csr_matrix

In [26]:
len(sorted_paths)

1075

In [21]:
path='/home/python/higashi/cool/contacts_map_250k/cortex/cortex_p1/cortex_p1_1/chr1.txt'
test=[int(part) if part.isdigit() else part for part in path.split('_')]

In [22]:
test

['/home/python/higashi/cool/contacts',
 'map',
 '250k/cortex/cortex',
 'p1/cortex',
 'p1',
 '1/chr1.txt']

In [24]:
path='/home/python/higashi/cool/contacts_map_250k/cortex/cortex_p1/cortex_p1_1/chr1.txt'
parts = []
for part in path.split('/'):
    parts.extend(part.split('_'))
test=[int(part) if part.isdigit() else part for part in parts]
test

['',
 'home',
 'python',
 'higashi',
 'cool',
 'contacts',
 'map',
 '250k',
 'cortex',
 'cortex',
 'p1',
 'cortex',
 'p1',
 1,
 'chr1.txt']